### ISSUE TITLE
Properly configure board peripherals

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/swtbahn-cli#30]
https://github.com/uniba-swt/swtbahn-cli/blob/cfcdd17e826ba967b756bca309a70595b04a22c5/configurations/swtbahn-standard/config.bahn#L99-L107

The peripherals should all be of type `peripheral`. Extend peripherals to support required GPIO port (high and low) address (`0x????`).

```
peripherals onecontrol1
  onebit sync1 0x06 port 0x0027
  onebit lanterns1 0x07 port 0x0018  # Exact port address is not essential
end

peripherals onecontrol2
  onebit sync2 0x06 port 0x0027
  onebit lanterns2 0x07 port 0x0018  # Exact port address is not essential
end
```

```yaml
peripherals:
  - id: sync2
    number: 0x06
    port: 0x0027
    aspects:
      - id: on
        value: 0x00
      - id: off
        value: 0x01
    initial: on
    type: onebit
  - id: lanterns2
    number: 0x07
    port: 0x0018
    aspects:
      - id: on
        value: 0x00
      - id: off
        value: 0x01
    initial: on
    type: onebit
```
